spring:
   mvc:
      pathmatch:
            matching-strategy: ANT_PATH_MATCHER
   security:
    user:
      name: satyam
      password: satyam123
   application:
    name: login-service
   zipkin:      base-url: http://localhost:9411/
   config:    import: configserver:http://localhost:8888
   data:
    mongodb:
      host: localhost
      port: 27017
      database: stocksdb

server:
  port: 8001

management:  endpoints:    web:      exposure:        include: "*"